<a href="https://colab.research.google.com/github/wileykendall101/ML-Project/blob/main/intro_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np

List

In [4]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[1, 2, 3, 4, 5]

Numpy array

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.16544872, 0.42505532, 0.80521663, 0.97376502],
       [0.53494959, 0.48051866, 0.17579195, 0.02506678],
       [0.47990948, 0.71590169, 0.09202166, 0.6585869 ]])

In [9]:
np1.dtype

dtype('float64')

Tensor

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.8717,  0.9760, -0.5243, -0.5164],
        [ 0.3507, -1.6262, -0.8389, -0.5869],
        [-0.4967, -0.7343, -0.7673, -0.8279]])

In [15]:
tensor_3d = torch.randn(3,4,2)
tensor_3d

tensor([[[-1.3047, -0.6263],
         [ 0.1470,  1.6925],
         [-2.0769,  0.3803],
         [ 0.8400, -0.6718]],

        [[ 0.4479, -1.1322],
         [ 0.2588, -0.5899],
         [-1.0521,  0.3802],
         [ 1.1169,  0.1578]],

        [[ 1.4226,  0.0899],
         [-0.9182,  0.6882],
         [-0.1431, -0.3542],
         [-0.3180,  1.3920]]])

In [16]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1654, 0.4251, 0.8052, 0.9738],
        [0.5349, 0.4805, 0.1758, 0.0251],
        [0.4799, 0.7159, 0.0920, 0.6586]], dtype=torch.float64)

Next vid

In [18]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch2[1] = 4141
my_torch2

tensor([[   0,    1,    2,    3,    4],
        [4141, 4141, 4141, 4141, 4141]])

In [25]:
# Slices
mytorch7 = torch.arange(10)
mytorch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
mytorch7[4]

tensor(4)

In [28]:
my_torch8 = mytorch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [36]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

Math ops

In [38]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [39]:
tensor_a + tensor_b
# torch.add(tensor_a, tensor_b) is equivalent
# tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

Building Neural Network

In [41]:
import torch
import torch.nn as nn #this is neural network
import torch.nn.functional as F #this allows for moving data forward

In [46]:
# create model class that inherits nn.Module

class Model(nn.Module):
  # input layer (4 features of flower) ->
  # Hidden layer1 w/ n nuerons --> H2 --> output (1/3 classes of iris)
  def __init__(self, in_features=4, h1=8, h2=9, out_features = 3):
    super().__init__() #instantiate our nn.Module
    self.fc1 = nn.Linear(in_features, h1, ) #fully connected 1 (layer)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x)) #rectified linear unite --> do smth, if output is less than 0 count it as 0 else use output
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x



In [47]:
# pick manual seed for randomization
torch.manual_seed(41)

# create instance of model
model = Model()
